language: python
python:
  - "3.4"
env:
  global:
    - NOTHING_HERE_SO_FAR=""
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python3 setup.py sdist
  - find ./dist -iname "*.tar.gz" -print0 | xargs -0 pip install
# command to run tests, e.g. python setup.py test
script:
  - python3 testModule.py
notifications:
  email: false